openapi: 3.0.3
info:
  title: openapi
  description: |-
    openapi
  version: 'v1'
servers:
  - url: "http://localhost:8080"
  - url: "https://microcks-microcks.apps.cluster-xvdzv.dynamic.redhatworkshops.io/rest/openapi/v1"
paths: {}
