openapi: 3.0.3
info:
  title: openapi
  description: |-
    openapi
  version: 'v1'
servers:
  - url: "http://localhost:8080"
  - url: "https://microcks-microcks.apps.cluster-xvdzv.dynamic.redhatworkshops.io/rest/openapi/v1"
paths:
    /products:
        get:
            tags:
                - product
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: "#/components/schemas/Product"
                            examples:
                                products:
                                    value:
                                        - id: 0
                                          title: The Comedy of Errors
                                          descriptionHtml: "<a
                                              href=\"https://en.wikipedia.org/wiki/The_Comedy_of_Errors\"\
                                              >Wikipedia Summary</a>: The Comedy
                                              of Errors is one of <b>William
                                              Shakespeare's</b> early plays. It
                                              is his shortest and one of his
                                              most farcical comedies, with a
                                              major part of the humour coming
                                              from slapstick and mistaken
                                              identity, in addition to puns and
                                              word play."
                    description: successful operation
            operationId: getProducts
            summary: List all products
            description: List all products available in the application with a minimum
                amount of information.
    "/products/{id}":
        get:
            tags:
                - product
            parameters:
                - name: id
                  description: Product id
                  schema:
                      format: int32
                      type: integer
                  in: path
                  required: true
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ProductDetails"
                    description: successful operation
                "400":
                    description: Invalid product id
            operationId: getProduct
            summary: Get individual product
            description: Get detailed information about an individual product with the given
                id.
    "/products/{id}/reviews":
        get:
            tags:
                - review
            parameters:
                - name: id
                  description: Product id
                  schema:
                      format: int32
                      type: integer
                  in: path
                  required: true
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ProductReviews"
                    description: successful operation
                "400":
                    description: Invalid product id
            operationId: getProductReviews
            summary: Get reviews for a product
            description: Get reviews for a product, including review text and possibly
                ratings information.
    "/products/{id}/ratings":
        get:
            tags:
                - rating
            parameters:
                - name: id
                  description: Product id
                  schema:
                      format: int32
                      type: integer
                  in: path
                  required: true
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/ProductRatings"
                    description: successful operation
                "400":
                    description: Invalid product id
            operationId: getProductRatings
            summary: Get ratings for a product
            description: Get ratings for a product, including stars and their color.
components:
    schemas:
        Product:
            description: Basic information about a product
            required:
                - descriptionHtml
                - id
                - title
            type: object
            properties:
                id:
                    format: int32
                    description: Product id
                    type: integer
                title:
                    description: Title of the book
                    type: string
                descriptionHtml:
                    description: Description of the book - may contain HTML tags
                    type: string
        ProductDetails:
            description: Detailed information about a product
            required:
                - ISBN-10
                - ISBN-13
                - author
                - id
                - language
                - pages
                - publisher
                - type
                - year
            type: object
            properties:
                id:
                    format: int32
                    description: Product id
                    type: integer
                publisher:
                    description: Publisher of the book
                    type: string
                language:
                    description: Language of the book
                    type: string
                author:
                    description: Author of the book
                    type: string
                ISBN-10:
                    description: ISBN-10 of the book
                    type: string
                ISBN-13:
                    description: ISBN-13 of the book
                    type: string
                year:
                    format: int32
                    description: Year the book was first published in
                    type: integer
                type:
                    description: Type of the book
                    enum:
                        - paperback
                        - hardcover
                    type: string
                pages:
                    format: int32
                    description: Number of pages of the book
                    type: integer
        ProductReviews:
            description: Object containing reviews for a product
            required:
                - id
                - reviews
            type: object
            properties:
                id:
                    format: int32
                    description: Product id
                    type: integer
                reviews:
                    description: List of reviews
                    type: array
                    items:
                        $ref: "#/components/schemas/Review"
        Review:
            description: Review of a product
            required:
                - reviewer
                - text
            type: object
            properties:
                reviewer:
                    description: Name of the reviewer
                    type: string
                text:
                    description: Review text
                    type: string
                rating:
                    $ref: "#/components/schemas/Rating"
        Rating:
            description: Rating of a product
            required:
                - color
                - stars
            type: object
            properties:
                stars:
                    format: int32
                    description: Number of stars
                    maximum: 5
                    minimum: 1
                    type: integer
                color:
                    description: Color in which stars should be displayed
                    enum:
                        - red
                        - black
                    type: string
        ProductRatings:
            description: Object containing ratings of a product
            required:
                - id
                - ratings
            type: object
            properties:
                id:
                    format: int32
                    description: Product id
                    type: integer
                ratings:
                    description: A hashmap where keys are reviewer names, values are number of stars
                    type: object
                    additionalProperties:
                        type: string
tags:
    - name: product
      description: Information about a product (in this case a book)
    - name: review
      description: Review information for a product
    - name: rating
      description: Rating information for a product
externalDocs:
    description: Learn more about the Istio BookInfo application
    url: https://istio.io/docs/samples/bookinfo.html
